shared:
  box: pdloader/OL78Base
  non_rotational: 'on'
  software_folder: 'F:\~Oracle Tutorial Folder\Software\OracleSoftware'
  domain_name: localdomain
  cluster_name: 'OL7D122RAC'
  cluster_node_count: 2
  public_subnet: 192.168.56.0
  private_subnet: 192.168.1.0
  dns_ip_address: 192.168.56.100
  cluster_ip_start: 192.168.56.100
  listener_port_start: 1530
  em_port_start: 5530
  host_only_adapter_name: 'VirtualBox Host-Only Ethernet Adapter'
  sata_controller_name: 'SATA'
  shared_disk_folder: 'F:\~Vagrant\VMDisks'
  u01_size_GB: 100
  ASM_DATA_filename: 'ASMDATA'
  ASM_DATA_disk_count: 7
  ASM_DATA_disk_size_GB: 10
  ASM_FRA_filename: 'ASMFRA'
  ASM_FRA_disk_count: 3
  ASM_FRA_disk_size_GB: 10

dns:
  mem_size: 1024
  cpus: 1
  
nodes:
  mem_size: 10240
  cpus: 4