# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

VAGRANTFILE_API_VERSION = "2"

params = YAML.load_file 'config/vagrant.yml'

var_shared_disk_folder      = params['shared']['shared_disk_folder']
var_box                     = params['shared']['box']
#ASM_LOC     = "F:\\~Vagrant\\VMDisks\\OL7D122RAC-2\\asmdisk"
num_disks   = 4
disk_size   = 1
servers     = 2
mem         = 4096
cpu         = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.box = var_box
config.ssh.forward_x11 = true
config.ssh.forward_agent = true

	(1..servers).each do |rac_id|
	config.vm.define "rac#{rac_id}" do |config|
	config.vm.hostname = "rac#{rac_id}"

	# Do Virtualbox configuration 
	config.vm.provider :virtualbox do |vb|
		
		# Change RAC node specific settings 
		vb.customize ['modifyvm', :id, '--cpus', cpu]
		vb.customize ['modifyvm', :id, '--memory', mem]  

		# Increase SATA port count 
		vb.customize ['storagectl', :id, '--name', 'SATA', '--portcount', 5]   
		
		(1..num_disks).each do |disk|
			if ARGV[0] == "up" && ! File.exist?(var_shared_disk_folder + "#{disk}.vdi")
				if rac_id == 1
					vb.customize ['createhd',
								'--filename', var_shared_disk_folder + "#{disk}.vdi",
								'--format', 'VDI',
								'--variant', 'Fixed',
								'--size', disk_size * 1024]
					vb.customize ['modifyhd',
								 var_shared_disk_folder + "#{disk}.vdi",
								'--type', 'shareable']
				end # End createmedium on rac1

				vb.customize ['storageattach', :id,
						'--storagectl', 'SATA',
						'--port', "#{disk}",
						'--device', 0,
						'--type', 'hdd',
						'--medium', var_shared_disk_folder + "#{disk}.vdi",
						'--nonrotational', 'on']
			end  # End if exist
		end    # End of EACH iterator for disks  
        
	end      # End of config.vm.provider
  
	# Create disk partitions   
	if rac_id ==  1
		config.vm.provision "shell", inline: <<-SHELL
		if [ -f /etc/SFDISK_CREATE_DATE ]; then
		 echo "Partition creation already done."
		  exit 0
		fi
		for i in `ls /dev/sd* | grep -v sda`;  do echo \\; | sudo sfdisk -q $i; done
		date > /etc/SFDISK_CREATE_DATE
		SHELL
	end # End create disk partions
	
		#if rac_id == servers
		#	# Start Ansible provisioning
		#	config.vm.provision "ansible" do |ansible|
		#		#ansible.verbose = "-v"
		#		ansible.limit = "all"
		#		ansible.playbook = "ansible/rac_gi_db.yml"
		#	end # End of Ansible provisioning
		#end
	
    end  # End define VM config
  end # End each iterator RAC hosts
end # End of Vagrant.configure